name: Django Unit Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 13181
          POSTGRES_DB: mock_server_lite
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_USER=${{ secrets.POSTGRES_DB_USER }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_HOST=${{ secrets.POSTGRES_DB_HOST }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_PORT=${{ secrets.POSTGRES_DB_PORT }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_PASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_OPTIONS=${{ secrets.POSTGRES_DB_OPTIONS }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_TEST_NAME=${{ secrets.POSTGRES_DB_TEST_NAME }}" >> $GITHUB_ENV
          echo "export DATABASE_URL=postgres://postgres:13181@localhost:5432/mock_server_lite" >> $GITHUB_ENV

      - name: Run Django unit tests
        run: python manage.py test
