name: Django Unit Test

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB_NAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_USER=${{ secrets.POSTGRES_DB_USER }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_HOST=${{ secrets.POSTGRES_DB_HOST }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_PORT=${{ secrets.POSTGRES_DB_PORT }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_PASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_OPTIONS=${{ secrets.POSTGRES_DB_OPTIONS }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_TEST_NAME=${{ secrets.POSTGRES_DB_TEST_NAME }}" >> $GITHUB_ENV
          echo "export DATABASE_URL=postgres://postgres:13181@localhost:5432/mock_server_lite" >> $GITHUB_ENV

      - name: Run Django unit tests
        run: python manage.py test


  build-and-push:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t mhasan09/mock_server_lite:latest .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push mhasan09/mock_server_lite:latest